spring:
  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 데이터 대소문자 구분

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/loan
    username: root
    password: root

  redis:
    host: loan-redis
    port: 6379